export const TermsContent = [
  {
    title: "1. Introduction to Astra AI",
    content: `Astra AI is a cutting-edge AI-powered development platform revolutionizing how developers and teams build software applications. Our advanced technology streamlines the development process, enhances productivity, and enables rapid application deployment. By using our services, you acknowledge and agree to these comprehensive terms and conditions, which govern your access to and use of our platform. Astra AI is committed to providing innovative solutions while maintaining the highest standards of service quality.`,
  },
  {
    title: "2. User Responsibilities",
    content: `Users must maintain strict confidentiality of their account credentials and are fully responsible for all activities occurring under their account. This includes securing access tokens, API keys, and any other authentication credentials. You agree to use the service exclusively for legal purposes and in compliance with all applicable laws and regulations. Users must not attempt to reverse engineer the platform, circumvent any security measures, or use the service in any way that could harm the platform or other users. Regular security audits of your integration points are recommended.`,
  },
  {
    title: "3. AI Code Generation",
    content: `The code generated by Astra AI is provided "as is" without warranty of any kind, either express or implied. Users are solely responsible for reviewing, testing, and validating any generated code before deployment to production environments. While our AI strives for optimal code quality, it's essential to verify the output against your specific requirements and security standards. We recommend implementing proper testing protocols, including unit tests, integration tests, and security scans. Users should maintain backup systems and follow industry best practices when implementing generated code.`,
  },
  {
    title: "4. Data Privacy",
    content: `We prioritize your privacy and maintain strict data protection protocols. Any code or data you share with Astra AI is processed according to our comprehensive privacy policy, utilizing enterprise-grade encryption and security measures. We do not share your private code or data with third parties without explicit consent. Our platform implements multiple layers of security, including data encryption at rest and in transit, regular security audits, and compliance with international data protection standards. Users retain full ownership of their intellectual property and generated code.`,
  },
  {
    title: "5. Service Limitations",
    content: `Astra AI may have usage limits and service interruptions based on system capacity and maintenance requirements. We reserve the right to modify, suspend, or discontinue features at any time to improve platform stability and performance. Our service level agreements (SLAs) detail specific uptime commitments and maintenance windows. Users are advised to implement appropriate fallback mechanisms and maintain local backups of critical code and data. We provide advance notice of scheduled maintenance and feature updates through our status page and notification system.`,
  },
] as const;
